name: fixcoba
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  fl_chart: ^0.40.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.3 # Tambahkan versi paket http di sini
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/logos/facebook.jpg
    - assets/logos/google.jpg
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf
